# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Box2D_config = debug
  ImGuizmo_config = debug
  yaml_cpp_config = debug
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  Checksum_config = debug
  freetype_config = debug
  msdfgen_config = debug
  msdf_atlas_gen_config = debug
  lua_config = debug
  rttr_config = debug
  Engine_config = debug
  Vertex_ScriptCore_config = debug
  Vertex_Editor_config = debug
  Sandbox_config = debug
endif
ifeq ($(config),release)
  Box2D_config = release
  ImGuizmo_config = release
  yaml_cpp_config = release
  GLFW_config = release
  Glad_config = release
  ImGui_config = release
  Checksum_config = release
  freetype_config = release
  msdfgen_config = release
  msdf_atlas_gen_config = release
  lua_config = release
  rttr_config = release
  Engine_config = release
  Vertex_ScriptCore_config = release
  Vertex_Editor_config = release
  Sandbox_config = release
endif
ifeq ($(config),dist)
  Box2D_config = dist
  ImGuizmo_config = dist
  yaml_cpp_config = dist
  GLFW_config = dist
  Glad_config = dist
  ImGui_config = dist
  Checksum_config = dist
  freetype_config = dist
  msdfgen_config = dist
  msdf_atlas_gen_config = dist
  lua_config = dist
  rttr_config = dist
  Engine_config = dist
  Vertex_ScriptCore_config = dist
  Vertex_Editor_config = dist
  Sandbox_config = dist
endif

PROJECTS := Box2D ImGuizmo yaml-cpp GLFW Glad ImGui Checksum freetype msdfgen msdf-atlas-gen lua rttr Engine Vertex-ScriptCore Vertex-Editor Sandbox

.PHONY: all clean help $(PROJECTS) Core Dependencies Misc

all: $(PROJECTS)

Core: Engine Vertex-Editor Vertex-ScriptCore

Dependencies: Box2D Checksum GLFW Glad ImGui ImGuizmo freetype lua msdf-atlas-gen msdfgen rttr yaml-cpp

Misc: Sandbox

Box2D:
ifneq (,$(Box2D_config))
	@echo "==== Building Box2D ($(Box2D_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/Box2D -f Makefile config=$(Box2D_config)
endif

ImGuizmo:
ifneq (,$(ImGuizmo_config))
	@echo "==== Building ImGuizmo ($(ImGuizmo_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/ImGuizmo -f Makefile config=$(ImGuizmo_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/yaml-cpp -f Makefile config=$(yaml_cpp_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/imgui -f Makefile config=$(ImGui_config)
endif

Checksum:
ifneq (,$(Checksum_config))
	@echo "==== Building Checksum ($(Checksum_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/checksum -f Makefile config=$(Checksum_config)
endif

freetype:
ifneq (,$(freetype_config))
	@echo "==== Building freetype ($(freetype_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/msdf-atlas-gen/msdfgen/freetype -f Makefile config=$(freetype_config)
endif

msdfgen: freetype
ifneq (,$(msdfgen_config))
	@echo "==== Building msdfgen ($(msdfgen_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/msdf-atlas-gen/msdfgen -f Makefile config=$(msdfgen_config)
endif

msdf-atlas-gen: msdfgen
ifneq (,$(msdf_atlas_gen_config))
	@echo "==== Building msdf-atlas-gen ($(msdf_atlas_gen_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/msdf-atlas-gen -f Makefile config=$(msdf_atlas_gen_config)
endif

lua:
ifneq (,$(lua_config))
	@echo "==== Building lua ($(lua_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/lua -f Makefile config=$(lua_config)
endif

rttr:
ifneq (,$(rttr_config))
	@echo "==== Building rttr ($(rttr_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/rttr -f Makefile config=$(rttr_config)
endif

Engine: Glad ImGui ImGuizmo msdf-atlas-gen msdfgen yaml-cpp Box2D lua rttr
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(Engine_config)
endif

Vertex-ScriptCore:
ifneq (,$(Vertex_ScriptCore_config))
	@echo "==== Building Vertex-ScriptCore ($(Vertex_ScriptCore_config)) ===="
	@${MAKE} --no-print-directory -C Vertex-ScriptCore -f Makefile config=$(Vertex_ScriptCore_config)
endif

Vertex-Editor: Engine ImGui
ifneq (,$(Vertex_Editor_config))
	@echo "==== Building Vertex-Editor ($(Vertex_Editor_config)) ===="
	@${MAKE} --no-print-directory -C Vertex-Editor -f Makefile config=$(Vertex_Editor_config)
endif

Sandbox: Engine
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engine/vendor/Box2D -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/ImGuizmo -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/yaml-cpp -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/checksum -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/msdf-atlas-gen/msdfgen/freetype -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/msdf-atlas-gen/msdfgen -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/msdf-atlas-gen -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/lua -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/rttr -f Makefile clean
	@${MAKE} --no-print-directory -C Engine -f Makefile clean
	@${MAKE} --no-print-directory -C Vertex-ScriptCore -f Makefile clean
	@${MAKE} --no-print-directory -C Vertex-Editor -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Box2D"
	@echo "   ImGuizmo"
	@echo "   yaml-cpp"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   Checksum"
	@echo "   freetype"
	@echo "   msdfgen"
	@echo "   msdf-atlas-gen"
	@echo "   lua"
	@echo "   rttr"
	@echo "   Engine"
	@echo "   Vertex-ScriptCore"
	@echo "   Vertex-Editor"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"