name: Build with VS2022 and Premake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version required for Setup.bat

    - name: Install Premake
      uses: Jarod42/install-premake5@v1  # This installs Premake5

    - name: Run Setup.bat script
      run: |
        cd scripts
        .\Setup.bat

    - name: Generate Visual Studio 2022 solution
      run: |
        premake5 vs2022

    - name: Build solution with MSBuild (Debug)
      run: |
        msbuild YourSolution.sln /p:Configuration=Debug

    - name: Build solution with MSBuild (Release)
      run: |
        msbuild YourSolution.sln /p:Configuration=Release

    - name: Build solution with MSBuild (Dist)
      run: |
        msbuild YourSolution.sln /p:Configuration=Dist
