name: Build with VS2022 Enterprise and Premake (x64)

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release, Dist]
        platform: [x64]
      fail-fast: false

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install Premake (if not cached)
      uses: Jarod42/install-premake5@v1

    - name: Run Setup.bat script
      run: |
        cd scripts
        .\Setup.bat

    - name: Generate Visual Studio 2022 solution
      run: |
        premake5 vs2022

    - name: Build Solution
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Vertex.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
