name: Build with VS2022 Enterprise and Premake (x64)

on:
  push:
    branches:
      - "**" # Match all branches, single '*' can cause issues
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release, Dist]
        platform: [x64]
      fail-fast: false

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Cache Premake Installation
      uses: actions/cache@v3
      id: premake
      with:
        path: ${{ github.workspace }}\.premake
        key: premake5-${{ runner.os }}-${{ hashFiles('scripts/Setup.bat') }}

    - name: Cache intermediate build files
      uses: actions/cache@v3
      with:
        path: bin-int
        key: ${{ runner.os }}-bin-int-${{ hashFiles('**/bin-int/**/*') }}
        restore-keys: |
          ${{ runner.os }}-bin-int-

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.216.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Cross, SPIRV-Tools, SPIRV-Reflect, SPIRV-Headers
        vulkan-use-cache: true

    - name: Install Premake (if not cached)
      if: steps.premake.outputs.cache-hit != 'true'
      uses: Jarod42/install-premake5@v1

    - name: Add Premake to PATH
      run: |
        echo "C:\\Program Files\\premake" >> $env:GITHUB_PATH

    - name: Run Setup.bat script
      run: |
        cd scripts
        .\Setup.bat

    - name: Generate Visual Studio 2022 solution
      run: premake5 vs2022

    - name: Build Solution
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Vertex.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /m /v:normal
