name: Build with VS2022 and Premake (x64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Cache Premake Installation
      uses: actions/cache@v3
      with:
        path: C:\Users\runneradmin\.premake5
        key: premake5-${{ runner.os }}-${{ hashFiles('scripts/Setup.bat') }}

    - name: Install Premake (if not cached)
      if: steps.cache.outputs.cache-hit != 'true'
      uses: Jarod42/install-premake5@v1

    - name: Run Setup.bat script
      run: |
        cd scripts
        .\Setup.bat

    - name: Generate Visual Studio 2022 solution
      run: |
        premake5 vs2022

    - name: Build Solution (Debug x64)
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Enterprise\Bin\MSBuild.exe" Vertex.sln /p:Configuration=Debug /p:Platform=x64

    - name: Build Solution (Release x64)
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Enterprise\Bin\MSBuild.exe" Vertex.sln /p:Configuration=Release /p:Platform=x64

    - name: Build Solution (Dist x64)
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Enterprise\Bin\MSBuild.exe" Vertex.sln /p:Configuration=Dist /p:Platform=x64
