name: Build with VS2022 Enterprise and Premake (x64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release, Dist]
        platform: [x64]
      fail-fast: false

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Cache Premake Installation
      uses: actions/cache@v3
      id: premake
      with:
        path: C:\Program Files\premake
        key: premake5-${{ runner.os }}-${{ hashFiles('scripts/Setup.bat') }}

    - name: Cache bin-int
      uses: actions/cache@v3
      with:
        path: bin-int
        key: ${{ runner.os }}-bin-int-${{ hashFiles('bin-int/**/*.*') }}
        restore-keys: ${{ runner.os }}-bin-int-

    - name: Install Premake (if not cached)
      if: steps.cache.premake.cache-hit != 'true'
      run: |
        # Check if Premake is already installed in the folder
        if (-Not (Test-Path -Path "C:\Program Files\premake\premake5.exe")) {
            # If Premake is not found, proceed with installation
            uses: Jarod42/install-premake5@v1
        }
        # Add Premake to the PATH environment variable
        echo "C:\\Program Files\\premake" >> $env:GITHUB_PATH

    - name: Run Setup.bat script
      run: |
        cd scripts
        .\Setup.bat

    - name: Generate Visual Studio 2022 solution
      run: |
        premake5 vs2022

    - name: Build Solution
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Vertex.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
